services:
  database:
    image: postgres
    env_file:
      - docker/env/project.env
    ports:
      - "5432:5432"

    volumes:
      - db-data:/var/lib/postgresql/data:rw

  app:
    build: docker/dockerfile/php-fpm
    env_file:
      - docker/env/project.env
    volumes:
      - ./application:/application
    working_dir: /application
    ports:
      - "8000:8000"
    depends_on:
      - database

  node:
    image: node
    volumes:
      - ./application:/application
    working_dir: /application

volumes:
  db-data:

networks:
  default:
    name: network